(ns ext.lang)

(def ^:private lang-eng
  {:notification {:env-applied   "Applied. Reload your window to activate the environment"
                  :env-available "The nix environment is available in your workspace"
                  :env-error     "Nix Env Selector: Failed to apply environment. See output channel for details."}
   :label        {:env-loading               "$(loading~spin) Applying environment..."
                  :env-selected              "$(beaker) Environment: %ENV_NAME%"
                  :env-custom                "custom"
                  :env-need-reload           "$(beaker) Need reload"
                  :select-config-placeholder "Select environment config"
                  :disabled-nix              "Disable Nix environment"
                  :reload                    "Reload"
                  :select-env                "Select"
                  :dismiss                   "Dismiss"
                  :show-logs                 "Show Error"
                  :info-title                "Nix Environment"
                  :info-section-current      "Current"
                  :info-section-actions      "Actions"
                  :info-status               "Status"
                  :info-status-active        "Active"
                  :info-status-disabled      "Disabled"
                  :info-source               "Source"
                  :info-path                 "Path"
                  :info-packages             "Packages"
                  :info-args                 "Args"
                  :info-shell-path           "nix-shell binary"
                  :info-flakes               "Use flakes"
                  :info-terminals            "Patch terminals"
                  :type-picker-placeholder   "Select environment type"
                  :type-picker-flake         "$(symbol-snippet) Use flake.nix"
                  :type-picker-nix-shell     "$(file-code) Use a nix-shell config"
                  :type-picker-no-files      "No .nix or flake.nix files found in workspace"
                  :info-log-level            "Log level"
                  :info-workspace            "Workspace"
                  :info-on                   "On"
                  :info-off                  "Off"
                  :info-source-flake         "flake"
                  :info-source-nix-shell     "nix-shell"
                  :info-source-packages      "packages"
                  :info-source-none          "none"
                  :info-flake-shell          "Flake shell"
                  :flake-shell-placeholder   "Select a devShell from your flake"
                  :flake-shell-default       "default"
                  :flake-shell-current       "current"
                  :flake-shell-none          "No devShells found in flake"
                  :flake-shell-list-failed   "Failed to list flake devShells. See output channel for details."
                  :action-sync               "$(sync) Sync environment"
                  :action-select             "$(list-flat) Select a different environment"
                  :action-disable            "$(circle-slash) Disable Nix environment"
                  :action-show-logs          "$(output) Show output channel"}})

(def lang lang-eng)
